.TH "com.antares.nfc.client.NfcDetectorActivity" 3 "Mon Nov 26 2012" "CS_340_Health_Survey_App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.antares.nfc.client.NfcDetectorActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity, and NfcIntentListener\&.
.PP
Inherited by \fBcom\&.antares\&.nfc\&.client\&.NfcWriterActivity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonNewIntent\fP (Intent intent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBonNfcFeatureNotFound\fP ()"
.br
.ti -1c
.RI "abstract void \fBonNfcFeatureFound\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NfcDetector \fBdetector\fP"
.br
.ti -1c
.RI "boolean \fBintentProcessed\fP = false"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static final String \fBTAG\fP = NfcDetectorActivity\&.class\&.getSimpleName()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract activity for detecting NFC tags\&.
.PP
\fBAuthor:\fP
.RS 4
Thomas Rorvik Skjolberg 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CS_340_Health_Survey_App from the source code\&.
